[package]
name = "network-semaphore"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
dashmap = "6.1.0"
system_shutdown = "4.0.1"
tokio = { version = "1.45.1", features = ["net", "macros", "rt", "time", "sync", "io-util"] }
